# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '11.0'

target 'CommonKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommonKit
  pod 'Moya/RxSwift', '~> 13.0.1'
  pod 'RxSwift', '~> 4.5.0'
  pod 'ObjectMapper','~> 3.5.1'
  pod 'SnapKit'

  target 'CommonKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommonKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
